package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import hep.crest.data.config.DatabasePropertyConfigurator;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GlobalTagMap generated by hbm2java.
 */
@Entity
@Table(name = "GLOBAL_TAG_MAP", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
@Accessors(fluent = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class GlobalTagMap implements java.io.Serializable {

    /**
     * Serializer.
     */
    private static final long serialVersionUID = -3535546379433341349L;
    /**
     * The global tag map ID.
     */
    @EmbeddedId
    @AttributeOverride(name = "globalTagName",
            column = @Column(name = "GLOBAL_TAG_NAME", nullable = false, length = 100))
    @AttributeOverride(name = "record",
            column = @Column(name = "RECORD", nullable = false, length = 100))
    @AttributeOverride(name = "label",
            column = @Column(name = "LABEL", nullable = false, length = 100))
    private GlobalTagMapId id;
    /**
     * The Tag.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TAG_NAME", nullable = false)
    private Tag tag;
    /**
     * The Global Tag.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GLOBAL_TAG_NAME", nullable = false, insertable = false, updatable = false)
    private GlobalTag globalTag;

}
