package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GlobalTagMapId generated by hbm2java.
 */
// This object represents an ID and it is embedded in GlobalTagMap.
// Define default constructors.
// Define equals and hashcode methods.
// These are essential for ID comparison.
@Embeddable
@Accessors(fluent = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class GlobalTagMapId implements java.io.Serializable {

    /**
     * Serializer.
     */
    private static final long serialVersionUID = -2041411292811311312L;
    /**
     * The global tag name.
     */
    @Column(name = "GLOBAL_TAG_NAME", nullable = false, length = 100)
    private String globalTagName;
    /**
     * The record. Used to identify a specific tag usage.
     */
    @Column(name = "RECORD", nullable = false, length = 100)
    private String record;
    /**
     * The label. It represent a generic tag name, similarly to COOL folder.
     */
    @Column(name = "LABEL", nullable = false, length = 100)
    private String label;

}
