package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IovId generated by hbm2java.
 */
// This object represents an ID and it is embedded in Iov.
// Define default constructors.
// Define equals and hashcode methods.
// These are essential for ID comparison.
@Embeddable
@Accessors(fluent = true)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode
public class IovId implements java.io.Serializable {

    /**
     * Serializer.
     */
    private static final long serialVersionUID = -2770785371714771938L;
    /**
     * The tag name.
     * This column should reference an existing Tag.
     */
    @Column(name = "TAG_NAME", nullable = false, length = 255)
    private String tagName;
    /**
     * The since time.
     * The concept of time is flexible: can be any kind of Long.
     */
    @Column(name = "SINCE", nullable = false, precision = 38, scale = 0)
    private BigDecimal since;
    /**
     * The insertion time.
     * This time is used to determine Iovs which were inserted before a snapshot time.
     */
    @Column(name = "INSERTION_TIME", nullable = false, length = 11)
    private Date insertionTime;
}
