package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import hep.crest.data.config.DatabasePropertyConfigurator;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import org.hibernate.annotations.Type;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import java.sql.Blob;

/**
 * Payload generated by hbm2java.
 */
@Entity
@Table(name = "PAYLOAD_DATA", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
// This object represents a Payload.
// Define default constructors.
@NoArgsConstructor
@Data
@Accessors(fluent = true)
public class PayloadData {

    /**
     * The hash.
     */
    @Id
    @Column(name = "HASH", unique = true, nullable = false, length = 64)
    private String hash;

    /**
     * The data blob. It will be transformed in a stream or byte array.
     */
    @Column(name = "DATA", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    private Blob data;
}
