package hep.crest.data.pojo;
// Generated Aug 2, 2016 3:50:25 PM by Hibernate Tools 3.2.2.GA

import java.sql.Blob;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;
import lombok.experimental.Accessors;
import org.hibernate.annotations.Type;

import hep.crest.data.config.DatabasePropertyConfigurator;

/**
 * Payload generated by hbm2java.
 */
@Entity
@Table(name = "TAG_META", schema = DatabasePropertyConfigurator.SCHEMA_NAME)
@Data
@Accessors(fluent = true)
public class TagMeta implements java.io.Serializable {

    /**
     * The serial id.
     */
    private static final long serialVersionUID = 5486724556389838782L;
    /**
     * The tag name.
     */
    @Id
    @Column(name = "TAG_NAME", unique = true, nullable = false, length = 255)
    private String tagName;
    /**
     * The description.
     */
    @Column(name = "DESCRIPTION", nullable = false, length = 512)
    private String description;
    /**
     * The number of channels.
     */
    @Column(name = "CHANNEL_SIZE")
    private Integer chansize;
    /**
     * The number of columns in the payload.
     */
    @Column(name = "COLUMN_SIZE")
    private Integer colsize;
    /**
     * The tag info json.
     */
    @Column(name = "TAG_INFO", nullable = false)
    @Lob
    @Type(type = "org.hibernate.type.BlobType")
    private Blob tagInfo;
    /**
     * The insertion time.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "INSERTION_TIME", nullable = false, updatable = true, length = 11)
    private Date insertionTime;


    /**
     * 
     * @return
     */
    @PrePersist
    public void prePersist() {
        if (this.insertionTime == null) {
            final Timestamp now = new Timestamp(new Date().getTime());
            this.insertionTime = now;
        }
    }

    /*
     * (non-Javadoc)
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "TagMeta [tagName=" + tagName + ", description=" + description + ", chansize="
                + chansize + ", colsize=" + colsize + ", insertionTime=" + insertionTime + "]";
    }
}
