openapi: 3.0.0

info:
  $ref: 'schemas/common.yml#/info'

servers:
  $ref: 'schemas/common.yml#/servers'

security:
  $ref: 'schemas/common.yml#/security'

tags:
  - name: iovs

paths:
  # tags
  /iovs:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs'
  /iovs/storebatch:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1storebatch'
  /iovs/selectSnapshot:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1selectSnapshot'
  /iovs/lastIov:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1lastIov'
  /iovs/selectIovPayloads:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1selectIovPayloads'
  /iovs/selectIovs:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1selectIovs'
  /iovs/selectGroups:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1selectGroups'
  /iovs/getSizeByTag:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1getSizeByTag'
  /iovs/getSize:
    $ref: 'crestdb_iovsapi.yml#/paths/~1iovs~1getSize'

components:
  securitySchemes:
    $ref: 'schemas/common.yml#/components/securitySchemes'
  requestBodies:
    $ref: 'schemas/common.yml#/components/requestBodies'

  schemas:
    # commons
    HTTPResponse:
      $ref: 'schemas/common.yml#/components/schemas/HTTPResponse'
    CrestBaseResponse:
      $ref: 'schemas/common.yml#/components/schemas/CrestBaseResponse'
    RespPage:
      $ref: 'schemas/common.yml#/components/schemas/RespPage'
    GenericMap:
      $ref: 'schemas/common.yml#/components/schemas/GenericMap'

    IovSetDto:
      $ref: 'schemas/iovs.yml#/components/schemas/IovSetDto'
    IovDto:
      $ref: 'schemas/iovs.yml#/components/schemas/IovDto'
    IovPayloadSetDto:
      $ref: 'schemas/iovs.yml#/components/schemas/IovPayloadSetDto'
    IovPayloadDto:
      $ref: 'schemas/iovs.yml#/components/schemas/IovPayloadDto'
