openapi: 3.0.0

info:
  $ref: 'schemas/common.yml#/info'

servers:
  $ref: 'schemas/common.yml#/servers'

security:
  $ref: 'schemas/common.yml#/security'

tags:
  - name: payloads

paths:
  # tags
  /payloads:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads'
  /payloads/{hash}:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1{hash}'
  /payloads/{hash}/meta:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1{hash}~1meta'
  /payloads/storebatch:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1storebatch'
  /payloads/uploadbatch:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1uploadbatch'
  /payloads/store:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1store'
  /payloads/upload:
    $ref: 'crestdb_payloadsapi.yml#/paths/~1payloads~1upload'

components:
  securitySchemes:
    $ref: 'schemas/common.yml#/components/securitySchemes'
  requestBodies:
    $ref: 'schemas/common.yml#/components/requestBodies'

  schemas:
    # commons
    HTTPResponse:
      $ref: 'schemas/common.yml#/components/schemas/HTTPResponse'
    CrestBaseResponse:
      $ref: 'schemas/common.yml#/components/schemas/CrestBaseResponse'
    RespPage:
      $ref: 'schemas/common.yml#/components/schemas/RespPage'
    GenericMap:
      $ref: 'schemas/common.yml#/components/schemas/GenericMap'

    PayloadSetDto:
      $ref: 'schemas/payloads.yml#/components/schemas/PayloadSetDto'
    PayloadDto:
      $ref: 'schemas/payloads.yml#/components/schemas/PayloadDto'
    IovSetDto:
      $ref: 'schemas/iovs.yml#/components/schemas/IovSetDto'
