# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
    datasource:
      trigger:
        jdbcUrl: ${crest.triggerdb.url}
        driverClassName: oracle.jdbc.OracleDriver
        username: ${crest.triggerdb.user}
        password: ${crest.triggerdb.password}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
          connection-test-query: SELECT 1 FROM DUAL
          maximum-pool-size: 10
