spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${crest.keycloak.url}/realms/${crest.keycloak.realm}
          jwk-set-uri: ${crest.keycloak.url}/realms/${crest.keycloak.realm}/protocol/openid-connect/certs
          # Optional: If using custom claim names
          claims-to-authorities-prefix: ROLE_
          authorities-claim-name: realm_access.roles

keycloak:
  client-id: ${crest.keycloak.client}
  client-secret: ${crest.keycloak.secret}
  auth-server-url: ${crest.keycloak.url}
  realm: ${crest.keycloak.realm}
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
