# ===============================
# = PROFILES /
#             server
#             ...
# ===============================
# Defaults
spring:
<<<<<<< HEAD
    autoconfigure:
      exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration
=======
>>>>>>> cms-2021
    config:
      use-legacy-processing: true
    profiles:
      include: crest
<<<<<<< HEAD
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
=======
>>>>>>> cms-2021
    jersey:
      application-path: ${crest.api.name}
    datasource:
      url: ${crest.db.url}
      driverClassName: org.postgresql.Driver
      username: ${crest.db.user}
      password: ${crest.db.password}
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 10
    jpa:
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate.jdbc.fetch_size: 300
# This should be changed for production to "validate"
<<<<<<< HEAD
        hibernate.hbm2ddl.auto: update
=======
        hibernate.hbm2ddl.auto: validate
>>>>>>> cms-2021
        hibernate.show_sql: false
        hibernate.jdbc.use_streams_for_binary: false
        hibernate.connection.autocommit: false
server:
    port: ${crest.server.port}
crest:
  schemaname: none
  dumpdir: ${crest.dump.dir}
  webstaticdir: ${crest.web.static}
  security: ${crest.server.security}
  synchro: none
  authenticationtype: none
  db:
    port: 5432
