/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * DataNotificationContent
 */
@JsonPropertyOrder({
  DataNotificationContent.JSON_PROPERTY_DATA_STREAM,
  DataNotificationContent.JSON_PROPERTY_DATA_PROVIDER,
  DataNotificationContent.JSON_PROPERTY_PRODUCT_CARD,
  DataNotificationContent.JSON_PROPERTY_DATE,
  DataNotificationContent.JSON_PROPERTY_MESSAGE,
  DataNotificationContent.JSON_PROPERTY_OBSID,
  DataNotificationContent.JSON_PROPERTY_RESOURCE_LOCATOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class DataNotificationContent   {
  public static final String JSON_PROPERTY_DATA_STREAM = "data_stream";
  @JsonProperty(JSON_PROPERTY_DATA_STREAM)
  private DataStream dataStream;

  public static final String JSON_PROPERTY_DATA_PROVIDER = "data_provider";
  @JsonProperty(JSON_PROPERTY_DATA_PROVIDER)
  private DataProvider dataProvider;

  public static final String JSON_PROPERTY_PRODUCT_CARD = "product_card";
  @JsonProperty(JSON_PROPERTY_PRODUCT_CARD)
  private String productCard;

  public static final String JSON_PROPERTY_DATE = "date";
  @JsonProperty(JSON_PROPERTY_DATE)
  private OffsetDateTime date;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  private String message;

  public static final String JSON_PROPERTY_OBSID = "obsid";
  @JsonProperty(JSON_PROPERTY_OBSID)
  private String obsid;

  public static final String JSON_PROPERTY_RESOURCE_LOCATOR = "resource_locator";
  @JsonProperty(JSON_PROPERTY_RESOURCE_LOCATOR)
  private String resourceLocator;

  public DataNotificationContent dataStream(DataStream dataStream) {
    this.dataStream = dataStream;
    return this;
  }

  /**
   * Get dataStream
   * @return dataStream
   **/
  @JsonProperty("data_stream")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public DataStream getDataStream() {
    return dataStream;
  }

  public void setDataStream(DataStream dataStream) {
    this.dataStream = dataStream;
  }

  public DataNotificationContent dataProvider(DataProvider dataProvider) {
    this.dataProvider = dataProvider;
    return this;
  }

  /**
   * Get dataProvider
   * @return dataProvider
   **/
  @JsonProperty("data_provider")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public DataProvider getDataProvider() {
    return dataProvider;
  }

  public void setDataProvider(DataProvider dataProvider) {
    this.dataProvider = dataProvider;
  }

  public DataNotificationContent productCard(String productCard) {
    this.productCard = productCard;
    return this;
  }

  /**
   * Get productCard
   * @return productCard
   **/
  @JsonProperty("product_card")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getProductCard() {
    return productCard;
  }

  public void setProductCard(String productCard) {
    this.productCard = productCard;
  }

  public DataNotificationContent date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Generic type for the Dates. Using Date as classname make the generator including java import in the Py code
   * @return date
   **/
  @JsonProperty("date")
  @ApiModelProperty(required = true, value = "Generic type for the Dates. Using Date as classname make the generator including java import in the Py code")
  @NotNull 
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public DataNotificationContent message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public DataNotificationContent obsid(String obsid) {
    this.obsid = obsid;
    return this;
  }

  /**
   * Get obsid
   * @return obsid
   **/
  @JsonProperty("obsid")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getObsid() {
    return obsid;
  }

  public void setObsid(String obsid) {
    this.obsid = obsid;
  }

  public DataNotificationContent resourceLocator(String resourceLocator) {
    this.resourceLocator = resourceLocator;
    return this;
  }

  /**
   * TBD
   * @return resourceLocator
   **/
  @JsonProperty("resource_locator")
  @ApiModelProperty(required = true, value = "TBD")
  @NotNull 
  public String getResourceLocator() {
    return resourceLocator;
  }

  public void setResourceLocator(String resourceLocator) {
    this.resourceLocator = resourceLocator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataNotificationContent dataNotificationContent = (DataNotificationContent) o;
    return Objects.equals(this.dataStream, dataNotificationContent.dataStream) &&
        Objects.equals(this.dataProvider, dataNotificationContent.dataProvider) &&
        Objects.equals(this.productCard, dataNotificationContent.productCard) &&
        Objects.equals(this.date, dataNotificationContent.date) &&
        Objects.equals(this.message, dataNotificationContent.message) &&
        Objects.equals(this.obsid, dataNotificationContent.obsid) &&
        Objects.equals(this.resourceLocator, dataNotificationContent.resourceLocator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataStream, dataProvider, productCard, date, message, obsid, resourceLocator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataNotificationContent {\n");
    
    sb.append("    dataStream: ").append(toIndentedString(dataStream)).append("\n");
    sb.append("    dataProvider: ").append(toIndentedString(dataProvider)).append("\n");
    sb.append("    productCard: ").append(toIndentedString(productCard)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    obsid: ").append(toIndentedString(obsid)).append("\n");
    sb.append("    resourceLocator: ").append(toIndentedString(resourceLocator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

