/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * Descriptor of spacecraft target e.g. OBSID or BURSTID
 */
@ApiModel(description = "Descriptor of spacecraft target e.g. OBSID or BURSTID")
@JsonPropertyOrder({
  DataGroup.JSON_PROPERTY_IDENTIFIER,
  DataGroup.JSON_PROPERTY_PROPERTY_CLASS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class DataGroup   {
  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  private String identifier;

  public static final String JSON_PROPERTY_PROPERTY_CLASS = "class";
  @JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)
  private DataGroupClass propertyClass;

  public DataGroup identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   **/
  @JsonProperty("identifier")
  @ApiModelProperty(value = "")
  
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public DataGroup propertyClass(DataGroupClass propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

  /**
   * Get propertyClass
   * @return propertyClass
   **/
  @JsonProperty("class")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public DataGroupClass getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(DataGroupClass propertyClass) {
    this.propertyClass = propertyClass;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataGroup dataGroup = (DataGroup) o;
    return Objects.equals(this.identifier, dataGroup.identifier) &&
        Objects.equals(this.propertyClass, dataGroup.propertyClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, propertyClass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataGroup {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

