/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DataResponseContainer
 */
@JsonPropertyOrder({
  DataResponseContainer.JSON_PROPERTY_DATA_REQUEST,
  DataResponseContainer.JSON_PROPERTY_DATA_FLAG,
  DataResponseContainer.JSON_PROPERTY_SIZE,
  DataResponseContainer.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class DataResponseContainer   {
  public static final String JSON_PROPERTY_DATA_REQUEST = "data_request";
  @JsonProperty(JSON_PROPERTY_DATA_REQUEST)
  private List<String> dataRequest = new ArrayList<>();

  public static final String JSON_PROPERTY_DATA_FLAG = "data_flag";
  @JsonProperty(JSON_PROPERTY_DATA_FLAG)
  private List<String> dataFlag = new ArrayList<>();

  public static final String JSON_PROPERTY_SIZE = "size";
  @JsonProperty(JSON_PROPERTY_SIZE)
  private Integer size;

  public static final String JSON_PROPERTY_DATA = "data";
  @JsonProperty(JSON_PROPERTY_DATA)
  private List<String> data = null;

  public DataResponseContainer dataRequest(List<String> dataRequest) {
    this.dataRequest = dataRequest;
    return this;
  }

  public DataResponseContainer addDataRequestItem(String dataRequestItem) {
    this.dataRequest.add(dataRequestItem);
    return this;
  }

  /**
   * Get dataRequest
   * @return dataRequest
   **/
  @JsonProperty("data_request")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public List<String> getDataRequest() {
    return dataRequest;
  }

  public void setDataRequest(List<String> dataRequest) {
    this.dataRequest = dataRequest;
  }

  public DataResponseContainer dataFlag(List<String> dataFlag) {
    this.dataFlag = dataFlag;
    return this;
  }

  public DataResponseContainer addDataFlagItem(String dataFlagItem) {
    this.dataFlag.add(dataFlagItem);
    return this;
  }

  /**
   * Get dataFlag
   * @return dataFlag
   **/
  @JsonProperty("data_flag")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public List<String> getDataFlag() {
    return dataFlag;
  }

  public void setDataFlag(List<String> dataFlag) {
    this.dataFlag = dataFlag;
  }

  public DataResponseContainer size(Integer size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   **/
  @JsonProperty("size")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public DataResponseContainer data(List<String> data) {
    this.data = data;
    return this;
  }

  public DataResponseContainer addDataItem(String dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Get data
   * @return data
   **/
  @JsonProperty("data")
  @ApiModelProperty(value = "")
  
  public List<String> getData() {
    return data;
  }

  public void setData(List<String> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataResponseContainer dataResponseContainer = (DataResponseContainer) o;
    return Objects.equals(this.dataRequest, dataResponseContainer.dataRequest) &&
        Objects.equals(this.dataFlag, dataResponseContainer.dataFlag) &&
        Objects.equals(this.size, dataResponseContainer.size) &&
        Objects.equals(this.data, dataResponseContainer.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataRequest, dataFlag, size, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataResponseContainer {\n");
    
    sb.append("    dataRequest: ").append(toIndentedString(dataRequest)).append("\n");
    sb.append("    dataFlag: ").append(toIndentedString(dataFlag)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

