/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * InfoMessageContent
 */
@JsonPropertyOrder({
  InfoMessageContent.JSON_PROPERTY_SERVICE_DESCRIPTOR,
  InfoMessageContent.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class InfoMessageContent   {
  public static final String JSON_PROPERTY_SERVICE_DESCRIPTOR = "service_descriptor";
  @JsonProperty(JSON_PROPERTY_SERVICE_DESCRIPTOR)
  private ServiceDescriptor serviceDescriptor;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  private String message;

  public InfoMessageContent serviceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
    return this;
  }

  /**
   * Get serviceDescriptor
   * @return serviceDescriptor
   **/
  @JsonProperty("service_descriptor")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public ServiceDescriptor getServiceDescriptor() {
    return serviceDescriptor;
  }

  public void setServiceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
  }

  public InfoMessageContent message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoMessageContent infoMessageContent = (InfoMessageContent) o;
    return Objects.equals(this.serviceDescriptor, infoMessageContent.serviceDescriptor) &&
        Objects.equals(this.message, infoMessageContent.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceDescriptor, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoMessageContent {\n");
    
    sb.append("    serviceDescriptor: ").append(toIndentedString(serviceDescriptor)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

