/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets Instrument
 */
public enum Instrument {
  
  MXT("MXT"),
  
  VT("VT"),
  
  ECL("ECL"),
  
  GRM("GRM"),
  
  PDPU("PDPU"),
  
  GWAC("GWAC"),
  
  CGFT("CGFT"),
  
  FGFT("FGFT"),
  
  FPL("FPL"),
  
  CPL("CPL"),
  
  IC("IC"),
  
  ECLGRM("ECLGRM"),
  
  NONE("None");

  private String value;

  Instrument(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Instrument fromValue(String value) {
    for (Instrument b : Instrument.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

