/*
 * VHF REST API setting in JAX-RS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets ObsMode
 */
public enum ObsMode {
  
  COREPROGRAM("CoreProgram"),
  
  GENERALPROGRAM("GeneralProgram"),
  
  TARGETOFOPPORTUNITY("TargetOfOpportunity"),
  
  ANY("Any"),
  
  NONE("None");

  private String value;

  ObsMode(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ObsMode fromValue(String text) {
    for (ObsMode b : ObsMode.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

