/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Processing startup acknowledgment
 */
@ApiModel(description = "Processing startup acknowledgment")
@JsonPropertyOrder({
  ProcessingAck.JSON_PROPERTY_MESSAGE_CLASS,
  ProcessingAck.JSON_PROPERTY_MESSAGE_DATE,
  ProcessingAck.JSON_PROPERTY_CONTENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class ProcessingAck   {
  /**
   * Gets or Sets messageClass
   */
  public enum MessageClassEnum {
    PROCESSINGACK("ProcessingAck");

    private String value;

    MessageClassEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MessageClassEnum fromValue(String value) {
      for (MessageClassEnum b : MessageClassEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MESSAGE_CLASS = "message_class";
  @JsonProperty(JSON_PROPERTY_MESSAGE_CLASS)
  private MessageClassEnum messageClass = MessageClassEnum.PROCESSINGACK;

  public static final String JSON_PROPERTY_MESSAGE_DATE = "message_date";
  @JsonProperty(JSON_PROPERTY_MESSAGE_DATE)
  private OffsetDateTime messageDate;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @JsonProperty(JSON_PROPERTY_CONTENT)
  private ProcessingAckContent content;

  public ProcessingAck messageClass(MessageClassEnum messageClass) {
    this.messageClass = messageClass;
    return this;
  }

  /**
   * Get messageClass
   * @return messageClass
   **/
  @JsonProperty("message_class")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public MessageClassEnum getMessageClass() {
    return messageClass;
  }

  public void setMessageClass(MessageClassEnum messageClass) {
    this.messageClass = messageClass;
  }

  public ProcessingAck messageDate(OffsetDateTime messageDate) {
    this.messageDate = messageDate;
    return this;
  }

  /**
   * Generic type for the Dates. Using Date as classname make the generator including java import in the Py code
   * @return messageDate
   **/
  @JsonProperty("message_date")
  @ApiModelProperty(required = true, value = "Generic type for the Dates. Using Date as classname make the generator including java import in the Py code")
  @NotNull 
  public OffsetDateTime getMessageDate() {
    return messageDate;
  }

  public void setMessageDate(OffsetDateTime messageDate) {
    this.messageDate = messageDate;
  }

  public ProcessingAck content(ProcessingAckContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   **/
  @JsonProperty("content")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public ProcessingAckContent getContent() {
    return content;
  }

  public void setContent(ProcessingAckContent content) {
    this.content = content;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessingAck processingAck = (ProcessingAck) o;
    return Objects.equals(this.messageClass, processingAck.messageClass) &&
        Objects.equals(this.messageDate, processingAck.messageDate) &&
        Objects.equals(this.content, processingAck.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageClass, messageDate, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessingAck {\n");
    
    sb.append("    messageClass: ").append(toIndentedString(messageClass)).append("\n");
    sb.append("    messageDate: ").append(toIndentedString(messageDate)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

