/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets Process
 */
public enum Process {
  
  OBLC_ECL("OBLC-ECL"),
  
  OBLC_GRM("OBLC-GRM"),
  
  OBTLOC_ECL("OBTLOC-ECL"),
  
  OBTLOC_GRM("OBTLOC-GRM"),
  
  OBPOS_MXT("OBPOS-MXT"),
  
  OBPHOTL_MXT("OBPHOTL-MXT"),
  
  OBPHOTMM_MXT("OBPHOTMM-MXT"),
  
  OBATT_VT("OBATT-VT"),
  
  OBFIND_VT("OBFIND-VT"),
  
  OBIM1B_VT("OBIM1B-VT"),
  
  QPO_VT("QPO-VT"),
  
  QTEMP_HR_ECL("QTEMP-HR-ECL"),
  
  QTEMP_HR_GRM("QTEMP-HR-GRM"),
  
  QHR_ECLGRM("QHR-ECLGRM"),
  
  QL_MXT("QL-MXT"),
  
  N1_NOTICE("N1-NOTICE"),
  
  N1B_NOTICE("N1B-NOTICE"),
  
  XBANDGP_MXT("XBANDGP-MXT"),
  
  XVHFCP_MXT("XVHFCP-MXT"),
  
  XBAND_L1("XBAND-L1"),
  
  XBANDGP_ECLAIRS_QLA1("XBANDGP-ECLAIRS-QLA1");

  private String value;

  Process(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Process fromValue(String value) {
    for (Process b : Process.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

