/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ServiceStatusContent
 */
@JsonPropertyOrder({
  ServiceStatusContent.JSON_PROPERTY_SERVICE_DESCRIPTOR,
  ServiceStatusContent.JSON_PROPERTY_ACTIVITY,
  ServiceStatusContent.JSON_PROPERTY_DATE,
  ServiceStatusContent.JSON_PROPERTY_STATUS,
  ServiceStatusContent.JSON_PROPERTY_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class ServiceStatusContent   {
  public static final String JSON_PROPERTY_SERVICE_DESCRIPTOR = "service_descriptor";
  @JsonProperty(JSON_PROPERTY_SERVICE_DESCRIPTOR)
  private ServiceDescriptor serviceDescriptor;

  public static final String JSON_PROPERTY_ACTIVITY = "activity";
  @JsonProperty(JSON_PROPERTY_ACTIVITY)
  private ProcStatus activity;

  public static final String JSON_PROPERTY_DATE = "date";
  @JsonProperty(JSON_PROPERTY_DATE)
  private OffsetDateTime date;

  public static final String JSON_PROPERTY_STATUS = "status";
  @JsonProperty(JSON_PROPERTY_STATUS)
  private PipelineStatus status;

  public static final String JSON_PROPERTY_INFO = "info";
  @JsonProperty(JSON_PROPERTY_INFO)
  private String info;

  public ServiceStatusContent serviceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
    return this;
  }

  /**
   * Get serviceDescriptor
   * @return serviceDescriptor
   **/
  @JsonProperty("service_descriptor")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public ServiceDescriptor getServiceDescriptor() {
    return serviceDescriptor;
  }

  public void setServiceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
  }

  public ServiceStatusContent activity(ProcStatus activity) {
    this.activity = activity;
    return this;
  }

  /**
   * Get activity
   * @return activity
   **/
  @JsonProperty("activity")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public ProcStatus getActivity() {
    return activity;
  }

  public void setActivity(ProcStatus activity) {
    this.activity = activity;
  }

  public ServiceStatusContent date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

  /**
   * Generic type for the Dates. Using Date as classname make the generator including java import in the Py code
   * @return date
   **/
  @JsonProperty("date")
  @ApiModelProperty(required = true, value = "Generic type for the Dates. Using Date as classname make the generator including java import in the Py code")
  @NotNull 
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public ServiceStatusContent status(PipelineStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public PipelineStatus getStatus() {
    return status;
  }

  public void setStatus(PipelineStatus status) {
    this.status = status;
  }

  public ServiceStatusContent info(String info) {
    this.info = info;
    return this;
  }

  /**
   * Additional information on current processing (free) 
   * @return info
   **/
  @JsonProperty("info")
  @ApiModelProperty(value = "Additional information on current processing (free) ")
  
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStatusContent serviceStatusContent = (ServiceStatusContent) o;
    return Objects.equals(this.serviceDescriptor, serviceStatusContent.serviceDescriptor) &&
        Objects.equals(this.activity, serviceStatusContent.activity) &&
        Objects.equals(this.date, serviceStatusContent.date) &&
        Objects.equals(this.status, serviceStatusContent.status) &&
        Objects.equals(this.info, serviceStatusContent.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceDescriptor, activity, date, status, info);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStatusContent {\n");
    
    sb.append("    serviceDescriptor: ").append(toIndentedString(serviceDescriptor)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

