/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ServiceReportContent
 */
@JsonPropertyOrder({
  ServiceReportContent.JSON_PROPERTY_SERVICE_DESCRIPTOR,
  ServiceReportContent.JSON_PROPERTY_SEQUENCES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class ServiceReportContent   {
  public static final String JSON_PROPERTY_SERVICE_DESCRIPTOR = "service_descriptor";
  @JsonProperty(JSON_PROPERTY_SERVICE_DESCRIPTOR)
  private ServiceDescriptor serviceDescriptor;

  public static final String JSON_PROPERTY_SEQUENCES = "sequences";
  @JsonProperty(JSON_PROPERTY_SEQUENCES)
  private List<ProcessingDescriptor> sequences = new ArrayList<>();

  public ServiceReportContent serviceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
    return this;
  }

  /**
   * Get serviceDescriptor
   * @return serviceDescriptor
   **/
  @JsonProperty("service_descriptor")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public ServiceDescriptor getServiceDescriptor() {
    return serviceDescriptor;
  }

  public void setServiceDescriptor(ServiceDescriptor serviceDescriptor) {
    this.serviceDescriptor = serviceDescriptor;
  }

  public ServiceReportContent sequences(List<ProcessingDescriptor> sequences) {
    this.sequences = sequences;
    return this;
  }

  public ServiceReportContent addSequencesItem(ProcessingDescriptor sequencesItem) {
    this.sequences.add(sequencesItem);
    return this;
  }

  /**
   * Get sequences
   * @return sequences
   **/
  @JsonProperty("sequences")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public List<ProcessingDescriptor> getSequences() {
    return sequences;
  }

  public void setSequences(List<ProcessingDescriptor> sequences) {
    this.sequences = sequences;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceReportContent serviceReportContent = (ServiceReportContent) o;
    return Objects.equals(this.serviceDescriptor, serviceReportContent.serviceDescriptor) &&
        Objects.equals(this.sequences, serviceReportContent.sequences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceDescriptor, sequences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceReportContent {\n");
    
    sb.append("    serviceDescriptor: ").append(toIndentedString(serviceDescriptor)).append("\n");
    sb.append("    sequences: ").append(toIndentedString(sequences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

