/*
 * VHF REST API setting in JAX-RS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets SvomServiceStatus
 */
public enum SvomServiceStatus {
  
  IDLE("Idle"),
  
  WAITING("Waiting"),
  
  RUNNING("Running"),
  
  STARTING("Starting"),
  
  STOPPING("Stopping");

  private String value;

  SvomServiceStatus(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SvomServiceStatus fromValue(String text) {
    for (SvomServiceStatus b : SvomServiceStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

