/*
 * Svom Message Model
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea.formica@cern.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package plugin.nats.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * Input data for pipeline processing
 */
@ApiModel(description = "Input data for pipeline processing")
@JsonPropertyOrder({
  Target.JSON_PROPERTY_COLLECTED_DATA,
  Target.JSON_PROPERTY_PROCESS,
  Target.JSON_PROPERTY_MESSAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class Target   {
  public static final String JSON_PROPERTY_COLLECTED_DATA = "collected_data";
  @JsonProperty(JSON_PROPERTY_COLLECTED_DATA)
  private DataGroup collectedData;

  public static final String JSON_PROPERTY_PROCESS = "process";
  @JsonProperty(JSON_PROPERTY_PROCESS)
  private Process process;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  private String message;

  public Target collectedData(DataGroup collectedData) {
    this.collectedData = collectedData;
    return this;
  }

  /**
   * Get collectedData
   * @return collectedData
   **/
  @JsonProperty("collected_data")
  @ApiModelProperty(value = "")
  @Valid 
  public DataGroup getCollectedData() {
    return collectedData;
  }

  public void setCollectedData(DataGroup collectedData) {
    this.collectedData = collectedData;
  }

  public Target process(Process process) {
    this.process = process;
    return this;
  }

  /**
   * Get process
   * @return process
   **/
  @JsonProperty("process")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public Process getProcess() {
    return process;
  }

  public void setProcess(Process process) {
    this.process = process;
  }

  public Target message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Target target = (Target) o;
    return Objects.equals(this.collectedData, target.collectedData) &&
        Objects.equals(this.process, target.process) &&
        Objects.equals(this.message, target.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collectedData, process, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Target {\n");
    
    sb.append("    collectedData: ").append(toIndentedString(collectedData)).append("\n");
    sb.append("    process: ").append(toIndentedString(process)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

